#ifndef _TOOLCHAIN_INTELLISENSE_SHIM_H_
#define _TOOLCHAIN_INTELLISENSE_SHIM_H_

/*
 * IntelliSense-only header. Never included by real builds.
 * Neutralizes XC8 language extensions that the VS Code C/C++ extension
 * (clang-based IntelliSense) cannot parse.
 *
 * Generated by `make env` (toolchain/scripts/env.py) and injected via
 * c_cpp_properties.json "forcedInclude". Safe to edit by hand — env.py
 * only adds the forcedInclude reference, it doesn't rewrite this file.
 */

/* XC8 interrupt syntax: __interrupt(irq(TMR2), high_priority) → (nothing) */
#define __interrupt(...)
#define irq(...)
#define high_priority
#define low_priority

/* XC8 absolute address placement: __at(0x03A) → (nothing) */
#define __at(...)

/* XC8 24-bit integer types (native to PIC18, no standard equivalent) */
typedef unsigned int __uint24;
typedef int __int24;

/* XC8 1-bit type (single-bit SFR access) */
typedef unsigned char __bit;

/* XC8 inline assembly (CLRWDT(), SLEEP(), etc.) */
#define __asm(...)

/* XC8 section placement: __section("auto_start") → (nothing) */
#define __section(...)

/* XC8 stringification helpers used in macro expansions */
#define ___mkstr(x)
#define ___mkstr1(x)

#endif /* _TOOLCHAIN_INTELLISENSE_SHIM_H_ */